config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/index'

  resources :articles
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  # Validation
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Validation
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  vlidates :email, :username, presence: true, uniqueness: { case_sensitive: false }
  vlidates :username, length: { minimum: 3, maximum: 25 }
  vlidates :email, length: { maximum: 105 }, format: { with : VALID_EMAIL_REGEX }

  has_many :articles

  before_save { self.email = email.downcase }

  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :show, :update, :destroy]

  def new
    @article = Article.new
  end

  def index
    @articles = Article.all
  end

  def create 
    @article = Article.new(article_params)

    if @article.save do
      flash[:notice] = "Article was created successfully."
      redirect_to @article
    end
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully."
      redirect_to @article
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    @article.destroy
    flash[:notice] = "Article was deleted successfully."
    redirect_to articles_path 
  end

  private
  def set_article 
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: @article, local: true) do |form| %>
  <div clss="form-group">
    <%= form.label :title %><br />
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div class="form-group mt-4">
    <%= form.label :description %><br />
    <%= form.text_area :description, class:"form-control", style: "height: 200px;" %>
  </div>

  <%= form.submit "Save", class: "btn btn-primary" %>

<% end %>

app/views/articles/edit.html.erb
<h1> Edit Article </h1>
<% if @article.errors.any? %>
  <h2> Could not create article </h2>
  <% @article.errors.full_messages.each do |error| %>
    <ul>
      <li><%= error %></li>
    </ul>
  <% end %>
<% end %>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Articles</h1>
 
<table>
  <thead>
    <tr>
      <th><strong>Title</strong></th>
      <th><strong>Description</strong></th>
      <th><strong>Actions</strong></th>
      <th></th>
    </tr>
  </thead>
 
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td>
          <a href="/articles/<%=article.id%>">Show</a>
          <a href="/articles/<%=article.id%>/edit">Edit</a>
          <%= link_to 'Delete', article_path(article), method: :delete %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-8">
      <h1> New Article </h1>
      <% if @article.errors.any? %>
        <h2> Could not create article </h2>
        <% @article.errors.full_messages.each do |error| %>
          <ul>
            <li><%= error %></li>
          </ul>
        <% end %>
      <% end %>

      <div class="mt-4">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.description %>
</p>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
<%= msg %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>